enum IK {
    IK_APOSTROPHE      = 39,       // Key: '
    IK_COMMA           = 44,       // Key: ,
    IK_MINUS           = 45,       // Key: -
    IK_PERIOD          = 46,       // Key: .
    IK_SLASH           = 47,       // Key: /
    IK_ZERO            = 48,       // Key: 0
    IK_ONE             = 49,       // Key: 1
    IK_TWO             = 50,       // Key: 2
    IK_THREE           = 51,       // Key: 3
    IK_FOUR            = 52,       // Key: 4
    IK_FIVE            = 53,       // Key: 5
    IK_SIX             = 54,       // Key: 6
    IK_SEVEN           = 55,       // Key: 7
    IK_EIGHT           = 56,       // Key: 8
    IK_NINE            = 57,       // Key: 9
    IK_SEMICOLON       = 59,       // Key: ;
    IK_EQUAL           = 61,       // Key: =
    IK_A               = 65,       // Key: A | a
    IK_B               = 66,       // Key: B | b
    IK_C               = 67,       // Key: C | c
    IK_D               = 68,       // Key: D | d
    IK_E               = 69,       // Key: E | e
    IK_F               = 70,       // Key: F | f
    IK_G               = 71,       // Key: G | g
    IK_H               = 72,       // Key: H | h
    IK_I               = 73,       // Key: I | i
    IK_J               = 74,       // Key: J | j
    IK_K               = 75,       // Key: K | k
    IK_L               = 76,       // Key: L | l
    IK_M               = 77,       // Key: M | m
    IK_N               = 78,       // Key: N | n
    IK_O               = 79,       // Key: O | o
    IK_P               = 80,       // Key: P | p
    IK_Q               = 81,       // Key: Q | q
    IK_R               = 82,       // Key: R | r
    IK_S               = 83,       // Key: S | s
    IK_T               = 84,       // Key: T | t
    IK_U               = 85,       // Key: U | u
    IK_V               = 86,       // Key: V | v
    IK_W               = 87,       // Key: W | w
    IK_X               = 88,       // Key: X | x
    IK_Y               = 89,       // Key: Y | y
    IK_Z               = 90,       // Key: Z | z
    IK_LEFT_BRACKET    = 91,       // Key: [
    IK_BACKSLASH       = 92,       // Key: '\'
    IK_RIGHT_BRACKET   = 93,       // Key: ]
    IK_GRAVE           = 96,       // Key: `
    // Function keys
    IK_SPACE           = 32,       // Key: Space
    IK_ESCAPE          = 256,      // Key: Esc
    IK_ENTER           = 257,      // Key: Enter
    IK_TAB             = 258,      // Key: Tab
    IK_BACKSPACE       = 259,      // Key: Backspace
    IK_INSERT          = 260,      // Key: Ins
    IK_DELETE          = 261,      // Key: Del
    IK_RIGHT           = 262,      // Key: Cursor right
    IK_LEFT            = 263,      // Key: Cursor left
    IK_DOWN            = 264,      // Key: Cursor down
    IK_UP              = 265,      // Key: Cursor up
    IK_PAGE_UP         = 266,      // Key: Page up
    IK_PAGE_DOWN       = 267,      // Key: Page down
    IK_HOME            = 268,      // Key: Home
    IK_END             = 269,      // Key: End
    IK_CAPS_LOCK       = 280,      // Key: Caps lock
    IK_SCROLL_LOCK     = 281,      // Key: Scroll down
    IK_NUM_LOCK        = 282,      // Key: Num lock
    IK_PRINT_SCREEN    = 283,      // Key: Print screen
    IK_PAUSE           = 284,      // Key: Pause
    IK_F1              = 290,      // Key: F1
    IK_F2              = 291,      // Key: F2
    IK_F3              = 292,      // Key: F3
    IK_F4              = 293,      // Key: F4
    IK_F5              = 294,      // Key: F5
    IK_F6              = 295,      // Key: F6
    IK_F7              = 296,      // Key: F7
    IK_F8              = 297,      // Key: F8
    IK_F9              = 298,      // Key: F9
    IK_F10             = 299,      // Key: F10
    IK_F11             = 300,      // Key: F11
    IK_F12             = 301,      // Key: F12
    IK_LEFT_SHIFT      = 340,      // Key: Shift left
    IK_LEFT_CONTROL    = 341,      // Key: Control left
    IK_LEFT_ALT        = 342,      // Key: Alt left
    IK_LEFT_SUPER      = 343,      // Key: Super left
    IK_RIGHT_SHIFT     = 344,      // Key: Shift right
    IK_RIGHT_CONTROL   = 345,      // Key: Control right
    IK_RIGHT_ALT       = 346,      // Key: Alt right
    IK_RIGHT_SUPER     = 347,      // Key: Super right
    IK_KB_MENU         = 348,      // Key: KB menu
    // Keypad keys
    IK_KP_0            = 320,      // Key: Keypad 0
    IK_KP_1            = 321,      // Key: Keypad 1
    IK_KP_2            = 322,      // Key: Keypad 2
    IK_KP_3            = 323,      // Key: Keypad 3
    IK_KP_4            = 324,      // Key: Keypad 4
    IK_KP_5            = 325,      // Key: Keypad 5
    IK_KP_6            = 326,      // Key: Keypad 6
    IK_KP_7            = 327,      // Key: Keypad 7
    IK_KP_8            = 328,      // Key: Keypad 8
    IK_KP_9            = 329,      // Key: Keypad 9
    IK_KP_DECIMAL      = 330,      // Key: Keypad .
    IK_KP_DIVIDE       = 331,      // Key: Keypad /
    IK_KP_MULTIPLY     = 332,      // Key: Keypad *
    IK_KP_SUBTRACT     = 333,      // Key: Keypad -
    IK_KP_ADD          = 334,      // Key: Keypad +
    IK_KP_ENTER        = 335,      // Key: Keypad Enter
    IK_KP_EQUAL        = 336,      // Key: Keypad =
    // Android key buttons
    IK_BACK            = 4,        // Key: Android back button
    IK_MENU            = 82,       // Key: Android menu button
    IK_VOLUME_UP       = 24,       // Key: Android volume up button
    IK_VOLUME_DOWN     = 25        // Key: Android volume down button
};
